url: "https://anirudhprabhakaran3.github.io"
baseurl: ""
title: "Anirudh Prabhakaran"

collections:
  news:
    output: false
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  research:
    output: true
    permalink: /research/:year/:month/:day/:title/

paginate: 1
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate